- type: playTimeTracker
  id: JobOffDutyCrew

- type: playTimeTracker
  id: JobMessChef

- type: playTimeTracker
  id: JobCustodian

- type: playTimeTracker
  id: JobHydroponicsBiologist

- type: playTimeTracker
  id: JobChiefOfMaintenance

- type: playTimeTracker
  id: JobMaintenanceTechnician

- type: playTimeTracker
  id: JobLifeSupportSpecialist

- type: playTimeTracker
  id: JobMaintenanceIntern
