- type: job
  id: LifeSupportSpecialist
  name: job-name-lifesupportspec
  description: job-description-lifesupportspec
  playTimeTracker: JobLifeSupportSpecialist
  setPreference: true # Frontier
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  weight: 110
  startingGear: LifeSupportSpecialistGear
  icon: "JobIconAtmosphericTechnician"
  supervisors: job-supervisors-com # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FirefighterDay
    prototype: FireAxe

- type: startingGear
  id: LifeSupportSpecialistGear
  equipment:
    eyes: ClothingEyesGlassesMeson
    id: AtmosPDA
#    belt: ClothingBeltUtilityEngineering # Frontier - Moved to locker
    ears: ClothingHeadsetEngineering
  #storage:
    #back:
    #- Stuff
