- type: job
  id: MaintenanceTechnician
  name: job-name-mainttech
  description: job-description-mainttech
  playTimeTracker: JobMaintenanceTechnician
  setPreference: true # Frontier
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  weight: 130
  startingGear: MaintenanceTechnicianGear
  icon: "JobIconStationEngineer"
  supervisors: job-supervisors-com # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: MaintenanceTechnicianGear
  equipment:
    eyes: ClothingEyesGlassesMeson
#    belt: ClothingBeltUtilityEngineering # Frontier - Moved to locker
    ears: ClothingHeadsetEngineering
  #storage:
    #back:
    #- Stuff
