- type: job
  id: Custodian
  name: job-name-custodian
  description: job-description-custodian
  playTimeTracker: JobCustodian
  setPreference: true # Frontier
  startingGear: CustodianGear
  icon: "JobIconCustodian"
  supervisors: job-supervisors-hop
  weight: 180
  displayWeight: 40
  canBeAntag: true
  # access: # Frontier
   # - Service # Frontier
   # - Janitor # Frontier
   # - Maintenance # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: GarbageDay
    prototype: WeaponRevolverInspector

- type: startingGear
  id: CustodianGear
  equipment:
    shoes: ClothingShoesGaloshes
    id: JanitorPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
  #storage:
    #back:
    #- Stuff
