- type: job
  id: HydroponicsBiologist
  name: job-name-hydroponics-biologist
  description: job-description-hydroponics-biologist
  playTimeTracker: JobHydroponicsBiologist
  setPreference: true # Frontier
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: HydroponicsBiologistGear
  icon: "JobIconHydroponicsBiologist"
  supervisors: job-supervisors-oo # Frontier
  weight: 190
  displayWeight: 50
  canBeAntag: true
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FourTwenty
    prototype: CannabisSeeds

- type: startingGear
  id: HydroponicsBiologistGear
  equipment:
    shoes: ClothingShoesColorBrown
    id: BotanistPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltPlantFilled
  #storage:
    #back:
    #- Stuff
